### ISSUE TITLE
Command complexity

### ISSUE THREAD

**Issue by Robotto** [openspaceaarhus/PhotonSaw#3]
java -Djava.library.path=/usr/lib/jni -cp /usr/share/java/RXTXcomm.jar:. -Ddw.machine.serialPort=/dev/ttyACM1 -jar target/shiver-0.0.1-SNAPSHOT.jar svg config.yaml

**Comment by dren-dk** [comment]
I just published a release with the newer and better rxtx replacement, so the first two options should not be needed any more.

Please see: https://github.com/openspaceaarhus/PhotonSaw/releases

I don't know what to do about the port parameter other than to say that the config.yaml file can be modified to get rid of it, perhaps we should have a wrapper script released along with the jar.

**Comment by Robotto** [comment]
Noice.

**Comment by Robotto** [comment]
Cool. So i know of the SVG mode, and the
